### ISSUE TITLE
Mispelled predefined variable.

### ISSUE THREAD

**Issue by pacrox** [X-Friese/FlyWithLua#74]
Although I'm NOT English mother tongue, I know that the word `HIGHT`, often used by americans, is totally wrong.
But FWL was made by a german guy, so a mistake is absolutely comprehensible.

![image](https://user-images.githubusercontent.com/36406936/111028321-320f7780-83f6-11eb-8614-36d6ad55cc2b.png)

Many many years ago I've reported the problem to X-Friese.
The guy was very kind in his answer, aknowledging the error. He even asked my suggestion of how to proceed, which I promptly gave.
![image](https://user-images.githubusercontent.com/36406936/111028218-9847ca80-83f5-11eb-89b6-f82f70d65487.png)

But probably the forum wasn't the best place to report this issue, thus, unfortunately, after 7 years from my report, nothing has changed.
https://github.com/X-Friese/FlyWithLua/blob/618a587543f47d6bec2369a745a435cf935668ac/src/FlyWithLua.cpp#L6469-L6470

I hope this helps.
Best.

Here is the link to forum's thread:
https://forums.x-plane.org/index.php?/forums/topic/80554-predefined-variables-mispelled/

**Comment by slgoldberg** [comment]
Just a thought... if someone is willing to do so, this could be a good tiny project for someone looking for experience with Open Source. :-)  It feels really straightforward: just bind a second predefined global to the same value either in the Internals/FlyWithLua.ini file, or someplace similar. (Just when the global is ready, have a master script that runs right away, and makes the alias.)

Though of course, I do agree (as a native US-English speaker) that it would be ideal if it was just fixed correctly -- HEIGHT instead of HIGHT -- but then we'd still need the alias so it doesn't break legacy scripts. (That could be done the same way as I describe above.)

   Steve

**Comment by sparker256** [comment]
So would this work by adding the correct name? I see it is used in two places in FlyWithLua.cpp.

1274   lua_pushnumber(FWLLua, LAST_SCREEN_HIGHT);
1275   lua_setglobal(FWLLua, "SCREEN_HIGHT");
          lua_setglobal(FWLLua, "SCREEN_HEIGHT");

6469   lua_pushnumber(FWLLua, LAST_SCREEN_HIGHT);
6470   lua_setglobal(FWLLua, "SCREEN_HIGHT");
          lua_setglobal(FWLLua, "SCREEN_HEIGHT");

Bill

**Comment by sparker256** [comment]
Version 2.7.29 now also supports the global variable SCREEN_HEIGHT.

I added a script in Scripts (disabled) folder called floating_wnd_demo_SCREEN_HEIGHT.lua using the new variable.

Hopefully I can get it uploaded to x-plane.org today so this issue can be closed.

Bill
